Repository unicode-org/icu4x, pull requests merged in 2022-08, with the labels that each got.

#2387 Check if the Swedish reformed collation exists
  provider/datagen/src/transform/icuexport/collator/mod.rs
Labels: C-data-infra, C-collator

#2398 Avoid cloning locales in DateTimeFormatter
  components/calendar/src/any_calendar.rs
  components/datetime/src/any/date.rs
  components/datetime/src/any/datetime.rs
  components/datetime/src/any/zoned_datetime.rs
  components/datetime/src/calendar.rs
  components/datetime/src/datetime.rs
  components/datetime/src/provider/date_time.rs
  components/datetime/src/raw/datetime.rs
  components/datetime/src/raw/zoned_datetime.rs
  components/datetime/src/zoned_datetime.rs
  components/datetime/tests/datetime.rs
Labels: discuss-priority

#2410 inline(always) trie accessors that are macros in ICU4C
  components/collections/src/codepointtrie/cptrie.rs
Labels: A-performance

#2378 Optimize normalizers for contiguous-memory input/output case
  Cargo.lock
  components/normalizer/Cargo.toml
  components/normalizer/fuzz/Cargo.lock
  components/normalizer/fuzz/Cargo.toml
  components/normalizer/fuzz/fuzz_targets/compare_self.rs
  components/normalizer/src/lib.rs
  components/normalizer/src/properties.rs
  components/normalizer/src/tests.rs
Labels: A-performance, C-collator

#2481 Use char instead of U24 in normalizer data
  components/collator/src/elements.rs
  components/normalizer/src/lib.rs
  components/normalizer/src/properties.rs
  components/normalizer/src/provider.rs
  components/normalizer/src/u24.rs
  provider/datagen/src/transform/icuexport/normalizer/mod.rs
  provider/testdata/data/json/fingerprints.csv
  provider/testdata/data/json/normalizer/decomp@1/und.json
  provider/testdata/data/json/normalizer/nfdex@1/und.json
  provider/testdata/data/json/normalizer/nfkdex@1/und.json
Labels: C-collator
