Repository unicode-org/icu4x, pull requests merged in 2024-09, with the labels that each got.

#5513 Introduce a borrowed version of the collator
  Cargo.lock
  components/collator/Cargo.toml
  components/collator/README.md
  components/collator/src/comparison.rs
  components/collator/src/lib.rs
  components/collator/tests/tests.rs
  ffi/capi/bindings/dart/Collator.g.dart
  ffi/capi/src/collator.rs
  provider/source/src/collator/mod.rs
  tools/make/diplomat-coverage/src/allowlist.rs
Labels: C-collator, 2.0-breaking

#5526 Change baked data constructors on owned normalizer types to follow conventions
  components/normalizer/src/lib.rs
  components/normalizer/src/uts46.rs
  components/normalizer/tests/tests.rs
  ffi/capi/src/normalizer.rs
  ffi/capi/tests/missing_apis.txt
  tools/make/diplomat-coverage/src/allowlist.rs
Labels: C-collator, 2.0-breaking

#5215 Change metacrate description for crates.io
  components/icu/Cargo.toml
Labels: waiting-on-author

#5306 Add references to LocaleCanonicalizer
  components/locale_core/src/langid.rs
  components/locale_core/src/locale.rs
Labels: needs-approval
