Repository unicode-org/icu4x, pull requests merged in 2025-02, with the labels that each got.

#6052 Remove some panics from zerovec's derive and icu_codepointtrie
  CHANGELOG.md
  components/collections/src/codepointtrie/cptrie.rs
  utils/zerovec/derive/src/make_varule.rs
  utils/zerovec/derive/src/ule.rs
  utils/zerovec/derive/src/varule.rs
Labels: U-android-bionic

#6088 Add Borrowed variants to casemapper types
  components/casemap/src/casemapper.rs
  components/casemap/src/closer.rs
  components/casemap/src/lib.rs
  components/casemap/src/set.rs
  components/casemap/src/titlecase.rs
  components/experimental/tests/transliterate/lower_ascii.rs
  ffi/capi/bindings/dart/CaseMapCloser.g.dart
  ffi/capi/bindings/dart/CaseMapper.g.dart
  ffi/capi/bindings/dart/TitlecaseMapper.g.dart
  ffi/capi/src/casemap.rs
  tools/make/diplomat-coverage/src/allowlist.rs
Labels: U-android-bionic

#5581 preserve stucture of timezone designation list
  utils/tzif/src/data/tzif.rs
  utils/tzif/src/parse/tzif.rs
Labels: waiting-on-author

#6211 Say more precisely what the IslamicCivil and IslamicTabular calendar variants are
  components/calendar/src/islamic.rs
Labels: C-calendar

#6209 Tweak the docs for Islamic calendrical calculations
  utils/calendrical_calculations/src/islamic.rs
Labels: C-calendar
